Repository SOPT-30th-Joint-Seminar-15/Client-iOS, pull requests merged in 2022-05, with the labels that each got.

#2 [#1] 프로젝트 파일 초기 세팅
  29cm-iOS/29cm-iOS.xcodeproj/project.pbxproj
  29cm-iOS/29cm-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  29cm-iOS/29cm-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  29cm-iOS/29cm-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  29cm-iOS/29cm-iOS/Info.plist
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/black01_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/black02_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/blue_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/box_grey_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/grey01_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/grey02_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/grey03_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/grey04_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/line_grey_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/red_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Colors.xcassets/white_29cm.colorset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Fonts/dummy.swift
  29cm-iOS/29cm-iOS/Resource/Storyboards/Base.lproj/LaunchScreen.storyboard
  29cm-iOS/29cm-iOS/Source/Application/AppDelegate.swift
  29cm-iOS/29cm-iOS/Source/Application/SceneDelegate.swift
  29cm-iOS/29cm-iOS/Source/Common/Consts/Color.swift
  29cm-iOS/29cm-iOS/Source/Common/Consts/Const.swift
  29cm-iOS/29cm-iOS/Source/Common/Extensions/Adjusted+.swift
  29cm-iOS/29cm-iOS/Source/Common/Extensions/CALayer+.swift
  29cm-iOS/29cm-iOS/Source/Common/Extensions/UITextField+.swift
  29cm-iOS/29cm-iOS/Source/Common/Extensions/UIView+.swift
  29cm-iOS/29cm-iOS/Source/Common/Extensions/UIViewController+.swift
  29cm-iOS/29cm-iOS/Source/Common/Protocols/Reusable.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Common/BaseViewController.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Controllers/HeeViewController.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Controllers/NeulViewController.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Models/HeeDataModel.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Models/NeulDataModel.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/HeeView.storyboard
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/NeulView.storyboard
  29cm-iOS/29cm-iOS/Source/Presentation/Read/Controllers/ReadViewController.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Read/Models/ReadDataModel.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Read/Views/ReadView.storyboard
Labels: set, 은희 🍋

#4 [#3] Image 에셋 및 Extension 추가
  29cm-iOS/29cm-iOS.xcodeproj/btnPhoto.svg
  29cm-iOS/29cm-iOS.xcodeproj/iPhoneX11ProLightBase.svg
  29cm-iOS/29cm-iOS.xcodeproj/icnBack.svg
  29cm-iOS/29cm-iOS.xcodeproj/icnButtonOff.svg
  29cm-iOS/29cm-iOS.xcodeproj/icnButtonOn.svg
  29cm-iOS/29cm-iOS.xcodeproj/icnMycart.svg
  29cm-iOS/29cm-iOS.xcodeproj/icnSearch.svg
  29cm-iOS/29cm-iOS.xcodeproj/icnSelectboxOff.svg
  29cm-iOS/29cm-iOS.xcodeproj/project.pbxproj
  29cm-iOS/29cm-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/btnPhoto.svg
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/iPhoneX11ProLightBase.svg
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/icnBack.svg
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/icnButtonOff.svg
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/icnButtonOn.svg
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/icnMycart.svg
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/icnSearch.svg
  29cm-iOS/29cm-iOS/Resource/Assets.xcassets/icnSelectboxOff.svg
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/btnPhoto.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/btnPhoto.imageset/btnPhoto.svg
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnBack.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnBack.imageset/icnBack.svg
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnButtonOff.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnButtonOff.imageset/icnButtonOff.svg
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnButtonOn.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnButtonOn.imageset/icnButtonOn.svg
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnMycart.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnMycart.imageset/icnMycart.svg
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnSearch.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnSearch.imageset/icnSearch.svg
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnSelectboxOff.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnSelectboxOff.imageset/icnSelectboxOff.svg
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnSelectboxOn.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnSelectboxOn.imageset/icnSelectboxOn.svg
  29cm-iOS/29cm-iOS/Source/Common/Consts/Image.swift
Labels: 지민 😺, set

#8 [#5] Custom NavigationBar 만들기
  29cm-iOS/29cm-iOS.xcodeproj/project.pbxproj
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/btnPhoto.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnBack.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnButtonOff.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnButtonOn.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnMycart.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnSearch.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnSelectboxOff.imageset/Contents.json
  29cm-iOS/29cm-iOS/Resource/Images.xcassets/icnSelectboxOn.imageset/Contents.json
  29cm-iOS/29cm-iOS/Source/Presentation/Common/NavigationBarView.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Common/NavigationBarView.xib
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Controllers/HeeViewController.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/HeeView.storyboard
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/NeulView.storyboard
  29cm-iOS/29cm-iOS/Source/Presentation/Read/Views/ReadView.storyboard
Labels: style, 은희 🍋

#13 [Style] CreateView 디자인 및 디자인 관련 클릭 이벤트 구현
  29cm-iOS/29cm-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  29cm-iOS/29cm-iOS/Info.plist
  29cm-iOS/29cm-iOS/Source/Presentation/Common/NavigationBarView.xib
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Controllers/NeulViewController.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/NeulView.storyboard
Labels: 하늘 🌥, feat, style

#16 [#9] CreateView UI 구성
  29cm-iOS/29cm-iOS.xcodeproj/project.pbxproj
  29cm-iOS/29cm-iOS/Source/Common/Extensions/UICollectionView+.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Common/BaseViewController.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Controllers/CompletionPopUpViewController.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Controllers/HeeViewController.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/Cells/Hee/CheckListCollectionViewCell.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/Cells/Hee/CheckListCollectionViewCell.xib
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/Cells/Hee/InputCollectionViewCell.swift
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/Cells/Hee/InputCollectionViewCell.xib
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/CompletionPopUpView.storyboard
  29cm-iOS/29cm-iOS/Source/Presentation/Create/Views/HeeView.storyboard
Labels: style, 은희 🍋
